version: '3.8'

services:
  plx-onboarding-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: plx-onboarding:dev
    container_name: plx-onboarding-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - plx-dev-network
    command: npm run dev

networks:
  plx-dev-network:
    driver: bridge
