version: '3.8'

services:
  plx-onboarding:
    build:
      context: .
      dockerfile: Dockerfile
    image: plx-onboarding:latest
    container_name: plx-onboarding-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    networks:
      - plx-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: plx-onboarding-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - plx-onboarding
    networks:
      - plx-network
    profiles:
      - production

networks:
  plx-network:
    driver: bridge

volumes:
  app_data:
